### ISSUE TITLE
RE2 Remake cutscenes running in slow motion

### ISSUE THREAD

**Issue by ghost** [Guy1524/wine#1]
Frame drops/slow motion are a issue with wine mfplat implementation.
While using the mf-install workaround it works as expected.

proton logs with +mfplat - Proton-5.6-GE-2
[steam-883710.log](https://github.com/Guy1524/wine/files/4525155/steam-883710.log)

**Comment by Guy1524** [comment]
Thanks, could you add +timestamp to WINEDEBUG and and include GST_DEBUG="7"?  This may make it even slower but it should help root out which part is slow.

**Comment by ghost** [comment]
[steam-883710.tar.gz](https://github.com/Guy1524/wine/files/4542654/steam-883710.tar.gz)

**Comment by Guy1524** [comment]
As I mentioned on VKx, this looks like a case of videoconvert being very slow.  We can increase the number of threads it uses, but even 4x better perf than what you're getting is pretty bad.

**Comment by ghost** [comment]
ORC time? :pregnant_woman:

**Comment by ghost** [comment]
a GE-PROTON build with ORC fixed all my issues
Closing it
