### ISSUE TITLE
Wrong MF_MT_AUDIO_CHANNEL_MASK -> channel-mask conversion

### ISSUE THREAD

**Issue by nsivov** [Guy1524/wine#12]
https://github.com/Guy1524/wine/blob/ed8e2738ed5790073fb50e45547f38c9fc752b46/dlls/winegstreamer/mfplat.c#L1527-L1530

This should be using 64bit int, because it's GST_TYPE_BITMASK.  Otherwise gst_caps_set_simple() crashes for me.

**Comment by Guy1524** [comment]
Thanks, updated.
