### ISSUE TITLE
wine --version is wrong

### ISSUE THREAD

**Issue by Lyle-Tafoya** [Guy1524/wine#3]
Current output: wine-3.15-12650-g6a74ac4442 (Staging)

**Comment by SpookySkeletons** [comment]
I get wine-5.5-1179-g6a74ac4442e (Staging)
On my build of the git.

What do you build it with?

**Comment by Guy1524** [comment]
Looks like it was because i didn't push tags, can you check now?

**Comment by lukashoracek** [comment]
> Looks like it was because i didn't push tags, can you check now?

That fixed it for me

**Comment by Lyle-Tafoya** [comment]
Yes, this seems to be resolved now.
