### ISSUE TITLE
Origin will not fully launch with Virtual Output in PulseAudio

### ISSUE THREAD

**Issue by HadetTheUndying** [Guy1524/wine#9]
This is one i banged my head against for about a week.

**Bug:**
I had Virtual Output for all of my Bluetooth Speaker in my house and it was preventing me from launching Origin. 

**Solution:**
In `paprefs` Uncheck this box and you're good.
![alt text](https://i.imgur.com/wmQittZ.png "bug1")

**Comment by Guy1524** [comment]
Very cool, however this doesn't seem to be related to this wine branch, can I close this issue?

**Comment by HadetTheUndying** [comment]
Woops did I I'll open this in the wrong place? I'll close, my bad.
